{{ if .Values.sasl.scram.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka.fullname" . }}
  labels:
    app: {{ include "kafka.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}

  {{/* - range $i, $e := until (int .Values.replicas) */}}
data:
  kafka_server_jaas.conf: |-
    // Info for Kafka to speak to other Kafkas
    KafkaServer {
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="admin"
        password="$SCRAM_ADMIN_PASSWORD";
    };

    // Info for Kafka to connect to Zookeeper
    Client {
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="super"
        password="adminsecret";
    };

    // Info for third-party clients to connect to Kafka
    // (This is currently only used for the tests)
    KafkaClient {
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="admin"
        password="$SCRAM_ADMIN_PASSWORD";
    };

  {{/* - end */}}
{{- end }}
